PROD-3523 - update urls -> dev
topcoder-platform/universal-navigation pull request #127
Opened 2023-01-12 09:33 UTC by vas3a

https://topcoder.atlassian.net/browse/PROD-3523

Updates the links in the navi

2023-01-12 17:06 UTC, testflyjets approved these changes

2023-01-12 18:13 UTC, brooketopcoder requested changes
There is confusion about what the source of truth for these URLs should be.

Most of these changes conflict with what I've been told is the correct source.

I have a requested that we fix this issue.

For now, we can't merge this.

2023-01-12 20:26 UTC, vas3a commented
Thanks @brooketopcoder ! I'll wait for confirmation!

2023-01-17 18:40 UTC, brooketopcoder commented
All URL fixes are completed in https://github.com/topcoder-platform/universal-navigation/pull/133 and https://github.com/topcoder-platform/universal-navigation/pull/128.

Closing this PR w/out merging

2023-01-17 18:40 UTC, closed without merging