MP-70 - User profile nudges & toasts
topcoder-platform/universal-navigation pull request #219
Opened 2023-06-30 16:41 UTC by vas3a

https://topcoder.atlassian.net/browse/MP-70 - profile nudge & completeness toasts

- Implements toasts to encourage users to complete they're profiles
- adds nudge on user profile icon that animates and shows a dot to indicate the "profile" is missing data
- frequency of showing nudge & toasts is handled through cookies
- the toasts are treated as separate logic and is loaded in a separate file in order to not delay the load of the uninav
- animations/assets are lazy loaded as needed (not bundled together with the JS)

2023-06-30 17:22 UTC, testflyjets requested changes
Some minor grammar fixes and variable naming. Also, where and how is % complete computed -- by the API?

2023-06-30 17:22 UTC, testflyjets commented on src/lib/nudge-app/config.ts
> +    message: 'Prove you not a robot by verifying a few details.',
Should be "Prove you **are** not a robot..."

2023-06-30 17:22 UTC, testflyjets commented on src/lib/nudge-app/config.ts
> +    message: 'Show off your all your hard work and amazing gigs.',
Should be "Show off ~~your~~ all your hard work..."

2023-06-30 17:22 UTC, testflyjets commented on src/lib/nudge-app/toast-manager.ts
> +    setCookie(TOAST_COOKIE, completednessData.showToast, 7);
Is 7 the number of days between showing toasts? Let's make this a variable so it's clear.

2023-07-02 19:11 UTC, vas3a commented
@testflyjets I addressed the issues above.
The `% complete` is computed on the api side.

2023-07-02 20:20 UTC, testflyjets approved these changes

2023-07-03 11:26 UTC, merged